#!/bin/dash

# Install a bunch of dependencies
#
sudo apt-get install \
  autoconf \
  automake \
  autotools-dev \
  bison \
  bzr \
  ccache \
  clang \
  curl \
  doxygen-latex \
  emacs \
  exuberant-ctags \
  flex \
  fonts-dejavu \
  git \
  global \
  gparted \
  graphviz \
  heirloom-mailx \
  libXpm-dev \
  libboost-all-dev \
  libdbus-1-dev \
  libgconf2-dev \
  libgif-dev \
  libgnutls-dev \
  libgpm-dev \
  libgtk2.0-dev \
  libjna-java \
  libjpeg-dev \
  libm17n-dev \
  libmagick++-dev \
  libotf-dev \
  librsvg2-dev \
  libtiff5-dev \
  libtinfo-dev \
  libx11-dev \
  libxml2-dev \
  llvm \
  mercurial \
  msmtp \
  network-manager-openconnect-gnome \
  texinfo \
  texlive-fonts-extra \
  unison-all-gtk \


sudo chmod a+w /ccc
CCACHE_DIR=/ccc ccache -F0 -M0
sudo mkdir -p /net/whs/homes

# Download my configuration and install it in my home directory
#
cd ~
git clone https://github.com/jsyjr/MyConfiguration.git
mv ~/MyConfiguration/{*,.[a-z]*} ~
rm -r ~/MyConfiguration ~/Documents ~/Music ~/Public ~/Templates ~/Videos ~/examples.desktop

# Install the Dina bitmapped font
#
sudo mkdir -p /usr/local/share/fonts/dina
sudo cp -r ~/.dinafont/dina /usr/local/share/fonts/dina
cd /etc/fonts/conf.d
sudo rm 70-no-bitmaps.conf
sudo ln -s ../conf.avail/70-yes-bitmaps.conf .

cd /tmp
wget http://sourceforge.net/projects/sourcecodepro.adobe/files/SourceCodePro_FontsOnly-1.017.zip
unzip SourceCodePro_FontsOnly-1.017.zip
sudo mkdir -p /usr/local/share/fonts/SourceCodePro
sudo cp /tmp/SourceCodePro_FontsOnly-1.017/OTF/* /usr/local/share/fonts/SourceCodePro
rm -rf /tmp/SourceCodePro*

sudo dpkg-reconfigure fontconfig-config
sudo dpkg-reconfigure fontconfig
sudo fc-cache
fc-list | grep Dina
fc-list | grep Source


# Create a directory for projects to be cloned
#
mkdir ~/repos

# Download and build suckless st (st-light, st-dark)
#
cd ~/repos
git clone http://git.suckless.org/st
cd st
~/bin/rebuild-st

# Download and build emacs
#
cd ~/repos
git clone git://git.savannah.gnu.org/emacs.git
cd emacs
./autogen.sh
~/bin/rebuild-emacs
xrdb ~/.Xresources
# sudo make install
# sudo update-alternatives \
#  --install /usr/bin/emacs                                                 emacs              /usr/local/emacs/bin/emacs 1 \
#  --slave   /usr/share/icons/hicolor/128x128/apps/emacs.png                emacs-128x128.png  /usr/local/emacs/share/icons/hicolor/128x128/apps/emacs.png \
#  --slave   /usr/share/icons/hicolor/16x16/apps/emacs.png                  emacs-16x16.png    /usr/local/emacs/share/icons/hicolor/16x16/apps/emacs.png \
#  --slave   /usr/share/icons/hicolor/24x24/apps/emacs.png                  emacs-24x24.png    /usr/local/emacs/share/icons/hicolor/24x24/apps/emacs.png \
#  --slave   /usr/share/icons/hicolor/32x32/apps/emacs.png                  emacs-32x32.png    /usr/local/emacs/share/icons/hicolor/32x32/apps/emacs.png \
#  --slave   /usr/share/icons/hicolor/48x48/apps/emacs.png                  emacs-48x48.png    /usr/local/emacs/share/icons/hicolor/48x48/apps/emacs.png \
#  --slave   /usr/share/icons/hicolor/scalable/mimetypes/emacs-document.svg emacs-document.svg /usr/local/emacs/share/icons/hicolor/scalable/mimetypes/emacs-document.svg \
#  --slave   /usr/share/man/man1/emacs.1.gz                                 emacs.1.gz         /usr/local/emacs/share/man/man1/emacs.1.gz \
#  --slave   /usr/share/icons/hicolor/scalable/apps/emacs.svg               emacs.svg          /usr/local/emacs/share/icons/hicolor/scalable/apps/emacs.svg \
#
# sudo update-alternatives \
#  --install /usr/bin/emacsclient                                           emacsclient        /usr/local/emacs/bin/emacsclient 1 \
#  --slave   /usr/share/man/man1/emacsclient.1.gz                           emacsclient.1.gz   /usr/local/emacs/share/man/man1/emacsclient.1.gz \
#
# sudo update-alternatives \
#  --install /usr/bin/ebrowse                                               ebrowse            /usr/local/emacs/bin/ebrowse 1 \
#  --slave   /usr/share/man/man1/ebrowse.1.gz                               ebrowse.1.gz       /usr/local/emacs/share/man/man1/ebrowse.1.gz \


# Download and build doxygen
#
cd ~/repos
git clone https://github.com/doxygen/doxygen.git
cd doxygen
~/bin/rebuild-doxygen
make -j8
# sudo make install

cat >~/.mailrc <<EOF
set from="john.yatess@sparqlcity.com"
set sendmail="/usr/bin/msmtp"
set message-sendmail-extra-arguments="-a gmail"
EOF

cat >~/.msmtp <<EOF
account gmail
host smtp.gmail.com
port 587
tls on
tls_trust_file /usr/share/ca-certificates/mozilla/Equifax_Secure_CA.crt
auth on

user john.yates@sparqlcity.com
from john.yates@sparqlcity.com
password ********

account default: gmail
EOF

cat >/tmp/fstab <<EOF
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system>                         <mount point>  <type>   <options>               <dump> <pass>
#
# /dev/sda
#
# /boot was on /dev/sda1 during installation
UUID=45383228-f8db-46aa-ab8a-248f219a4878   /boot       ext4    relatime,nodiratime          0 2
# /var was on /dev/sda2 during installation
UUID=bc626005-2d72-4ad9-b92c-57190da8de8f   /var        ext4    relatime,nodiratime          0 2
# swap was on /dev/sda3 during installation
UUID=5edf0681-dbe7-4334-b2da-17e278304fc1   none        swap    sw                           0 0
# /bulk was on /dev/sda4 during installation
UUID=ee510215-f3a4-4894-9e66-623b2c0a760c   /bulk       ext4    async,data=writeback,barrier=0,nouser_xattr,noacl,journal_async_commit,delalloc,max_batch_time=50000,noauto_da_alloc,dioread_nolock,noatime,nodiratime,discard  0 2
#
# /dev/sdb
#
# / was on /dev/sdb1 during installation
UUID=2b529276-47f7-4c04-bc6e-c68692a2787d   /           ext4    relatime,nodiratime,discard  0 1
# /ccache was on /dev/sdb2 during installation
UUID=32f76819-6490-4814-9d66-484a734cc403   /ccc        ext4    async,data=writeback,barrier=0,nouser_xattr,noacl,journal_async_commit,delalloc,max_batch_time=50000,noauto_da_alloc,dioread_nolock,noatime,nodiratime,discard  0 2
# /spare0 was on /dev/sdb3 during installation
UUID=f0c73aca-c916-4391-b498-9b0f57020c8a   /spare0     ext4    noatime,nodiratime,discard   0 2
#
# /dev/sdc
#
# /home was on /dev/sdc1 during installation
UUID=7fa16b1f-e6f2-47a3-901c-5781b4782480   /home       ext4    relatime,nodiratime,discard  0 2
# /ssd-cache was on /dev/sdc2 during installation
UUID=cdc593d1-ad42-48db-a44e-43b959bc10b5   /ssd-cache  ext4    relatime,nodiratime,discard  0 2
# /spare1 was on /dev/sdc3 during installation
UUID=b67dae08-d68d-4062-b6b9-905aa92a85b7   /spare1     ext4    noatime,nodiratime,discard   0 2
#
# TMPFS
#
none                                      /tmp        tmpfs   noatime,nodiratime             0 0
none                                      /var/tmp    tmpfs   relatime,nodiratime            0 0
#
# Network mounts  [ paren eFy wed jSy ]
#
//10.1.1.2/homes   /net/whs/homes  cifs   defaults,username=Dad,password=paren eFy wed jSy   0 2
EOF
