#!/bin/dash

# Install a bunch of dependencies
#
sudo apt-get install \
  autoconf \
  automake \
  autotools-dev \
  bsd-mailx \
  bzr \
  ccache \
  clang \
  curl \
  doxygen-latex \
  emacs \
  flex \
  fonts-dejavu \
  git \
  gparted \
  graphviz \
  libXpm-dev \
  libdbus-1-dev \
  libgconf2-dev \
  libgif-dev \
  libgnutls-dev \
  libgpm-dev \
  libgtk2.0-dev \
  libjna-java \
  libjpeg-dev \
  libm17n-dev \
  libmagick++-dev \
  libotf-dev \
  librsvg2-dev \
  libtiff5-dev \
  libtinfo-dev \
  libx11-dev \
  libxml2-dev \
  llvm \
  mercurial \
  network-manager-openconnect-gnome \
  texinfo \
  texlive-fonts-extra \
  unison-all-gtk \



# Download my configuration and install it in my home directory
#
cd ~
git clone https://github.com/jsyjr/MyConfiguration.git
mv ~/MyConfiguration/{*,.[a-z]*} ~
rm -r ~/MyConfiguration

# Install the Dina bitmapped font
#
sudo mkdir -p /usr/local/share/fonts/dina
sudo cp -r ~/.dinafont/dina /usr/local/share/fonts/dina
cd /etc/fonts/conf.d
sudo rm 70-no-bitmaps.conf
sudo ln -s ../conf.avail/70-yes-bitmaps.conf .

cd /tmp
wget http://sourceforge.net/projects/sourcecodepro.adobe/files/SourceCodePro_FontsOnly-1.017.zip
unzip SourceCodePro_FontsOnly-1.017.zip
sudo mkdir -p /usr/local/share/fonts/SourceCodePro
sudo cp /tmp/SourceCodePro_FontsOnly-1.017/OTF/* /usr/local/share/fonts/SourceCodePro
rm -rf /tmp/SourceCodePro*

sudo dpkg-reconfigure fontconfig-config
sudo dpkg-reconfigure fontconfig
sudo fc-cache
fc-list | grep Dina
fc-list | grep Source


# Create a directory for projects to be cloned
#
mkdir ~/repos

# Download and build suckless st (st-light, st-dark)
#
cd ~/repos
git clone http://git.suckless.org/st
cd st
~/bin/rebuild-st

# Download and build emacs
#
cd ~/repos
git clone git://git.savannah.gnu.org/emacs.git
cd emacs
./autogen.sh
~/bin/rebuild-emacs

# Download and build doxygen
#
cd ~/repos
git clone https://github.com/doxygen/doxygen.git
!/bin/rebuild-doxygen
make -j8
# make install
