#!/usr/bin/env python

import sys
import os

from subprocess import check_call

repoLocation = os.getcwd()
repoName = os.path.basename(repoLocation)

try:
    check_call('ssh savadhan@savadhan-deb6-64'.split() + [repoName, repoLocation])
except:
    sys.exit(1)

check_call('git fetch origin'.split())
