#!/usr/bin/env python

from commands import getoutput
from subprocess import call
import re

output = getoutput('p4 opened')
for line in output.splitlines():
    m = re.match(r'//mw/B\w+/(matlab/.*)#.*', line)
    if not m:
        continue

    filename = m.group(1)
    call(['p4', 'revert', '-k', filename])
    call(['p4', 'reconcile', filename])
