#!/usr/bin/env python

from commands import getoutput
import re
import os

args = []
fails = getoutput('ls *retry*')
for fname in fails.splitlines():
    args += ['*test%s*' % re.search(r'\d+', fname).group()]

os.system('sbscanlog -ohtml sbtest/res.html %s' % ' '.join(args))
