#!/usr/bin/env python2.7

import sys
import subprocess
from os import path
import os
import argparse
import sys

def die(message):
    sys.stderr.write('Error! %s\n' % message)
    sys.exit(1)

def run_cmd(cmd):
    print cmd
    subprocess.check_call(cmd.split())

parser = argparse.ArgumentParser(description = "sbcopy a sandbox and then start sbruntests")
parser.add_argument('-copy', required=True, metavar="LOCAL_SB_LOC", help="original sandbox location")

(options, sbrun_args) = parser.parse_known_args()

orig_sandbox = ''
sb_name = ''
if options.copy:
    orig_sandbox = path.abspath(options.copy)
    (dummy, sb_name) = path.split(orig_sandbox)
    if not path.isfile(path.join(orig_sandbox, 'battree')):
        die('%s is not a valid sandbox' % orig_sandbox)

run_cmd('sbcopy %s .' % orig_sandbox)
run_cmd('restoreDebugFiles.py')

testlogarea = path.join('/sandbox', os.getenv('USER'), 'sbruntests', sb_name)
sbrun_args = ' '.join(sbrun_args)
run_cmd('sbruntests -autofarm devel -rerunusing jobarchive -testlogarea %(testlogarea)s %(sbrun_args)s' % locals())
