#!/usr/bin/env bash

backingStores=`sbver | grep -Pzo "(?s)(?<=SyncFromBackingStore:).*(?=PerfectBackingStore)"`
dbgFiles="m_interpreter m_dispatcher m_ir"

for dbgFile in $dbgFiles; do
    for store in $backingStores; do
        relPath="matlab/bin/glnxa64/libmw${dbgFile}.so.dbg"
        if [ -f "${store}/${relPath}" ]; then
            echo "Copying ${relPath} from ${store}"
            cp "${store}/${relPath}" "$relPath" 
        fi
    done
done
