#!/bin/bash

if [ $# -lt 1 ]
then
    echo "Usage: $0 <new-sandbox-name> [<cluster>]"
    exit 1
fi

sbname=$1
if [ $# -lt 2 ]
then
    cluster=${ZFS_MASTER_SB%% *}
else
    cluster=$2
fi

echo "Creating a ZFS clone of last syned ${cluster}:latest_pass"

localSSDType=`blkid /dev/sdb1 | sed 's/.*TYPE="\(.*\)"/\1/'`
if [ $localSSDType == "btrfs" ]; then
    cd /local-ssd/$USER
    btrfs subvolume snapshot $cluster $sbname
else
    if [ -f /local-ssd/$USER/latest_snap_${cluster}.txt ]; then
        sudo zfs clone `cat /local-ssd/$USER/latest_snap_$cluster.txt` local-ssd/$USER/$sbname
    else
        echo "/local-ssd/$USER/latest_snap_${cluster}.txt does not exist.  Please create it by running zfs-sync-latest-pass"
        exit 1
    fi
fi

cd /local-ssd/$USER/$sbname
evil_fix_clone
echo "Sandbox /local-ssd/$USER/$1 is ready to use!"
