#!/bin/dash

# First argument
# The intent of these .ignores is to include all code mentioned in cg_ir/ez.mk:
#
# $ROOT                 <ROOT>/
#                       │
# $CLUSTER_ROOT         ├── .cluster/
# $CLUSTER_PATH             └── <CLUSTER>/
# $CLUSTER_GIT_REPO             ├── git/
# $CLUSTER_LATEST_PASS          └── <CLUSTER>.latest_pass/
#                                    ├── config
#                                    └── matlab
#                                        ├── src
#                                        │   ├── cg_ir
#                                        │   ├── cgir_*
#                                        │   ├── dnn_core
#                                        │   ├── eml
#                                        │   ├── emlcode
#                                        │   ├── half_precision
#                                        │   ├── include
#                                        │   ├── pir_core
#                                        │   ├── range_services
#                                        │   ├── rtw*
#                                        │   ├── slcg
#                                        │   ├── slcg_cpp
#                                        │   │   └── client
#                                        │   ├── slcg_driver
#                                        │   ├── slcg_fe
#                                        │   ├── slcg_filepackaging
#                                        │   ├── slcg_identifiers
#                                        │   ├── slcg_mf0
#                                        │   ├── slvm
#                                        │   └── xil_utils
#                                        ├── test
#                                        │   └── toolbox
#                                        │       ├── cgir
#                                        │       ├── cgir_web_interface
#                                        │       └── cpp_perf_tests
#                                        └── toolbox
#                                            ├── cgir
#                                            ├── coder
#                                            │   ├── codedescriptor_core
#                                            │   └── foundation
#                                            └── shared
#                                                ├── cgir_fe
#                                                ├── cgxe
#                                                └── cxxfe

append_gitignore_lines() {
    GITIGNORE_PATH=$1.gitignore
    if [ -e $GITIGNORE_PATH ] ; then
        chmod a+w $GITIGNORE_PATH
        echo    >>$GITIGNORE_PATH
    else
        touch     $GITIGNORE_PATH
    fi
    echo >>$GITIGNORE_PATH
    echo >>$GITIGNORE_PATH "# Rules added by syncmaster's add-git-ignore-files"
    echo >>$GITIGNORE_PATH
    cat  >>$GITIGNORE_PATH

    cat  >>$GITIGNORE_PATH <<EOF


# Directories (anywhere, no exceptions)
#
.ts/
*.xcodeproj/


# Files (anywhere, no exceptions)
#
.gdb_history
.validate_dox.ts
jar_extract_*
LKG_*
_mkgraph_dump.viz
sbcpptags.cfg
sbpatch_history_sbclone
viterbi_block.*


# Extensions typically signalling binary or derived data (anywhere, no exceptions)
*.0*
*.1*
*.2*
*.3*
*.4*
*.5*
*.6*
*.7*
*.8*
*.9*
*.CHM
*.EXE
*.FNT
*.GIF
*.HTML
*.HTMT
*.HTMTX
*.ICO
*.JPEG
*.JPG
*.LIB
*.OBJ
*.P
*.PDFTX
*.PNG
*.TIFF
*.TTF
*.Tiffile
*.Z
*.a
*.avi
*.bmp
*.bz2
*.chm
*.cpp.gen
*.exe
*.fmt
*.fnt
*.gif
*.hpp.gen
*.htm
*.html*
*.htmt
*.htmtx
*.htmx
*.ico
*.jar
*.jp2
*.jpeg
*.jpg
*.lib
*.mat
*.mdzip
*.mex*
*.mov
*.mp3
*.mp4
*.mpa
*.mpeg
*.mpg
*.msi
*.o
*.obj
*.ocx
*.ogg
*.otf
*.p
*.pcf
*.pch
*.pcm
*.pcx
*.pdb
*.pdf*
*.png
*.ppm
*.ppt
*.pptx
*.prj
*.ps
*.sbrestore.tmp
*.slx
*.so
*.svg
*.svgz
*.swo
*.swp
*.tar
*.tgz
*.thumbnail
*.tif
*.tiff
*.tiff2dib
*.tiffile
*.tmp
*.ttf
*.vcXproj
*.vcproj
*.vcwin32
*.vcxproj
*.vhd
*.wixproj
*.wma
*.wmf
*.wmt
*.wmv
*.xcconfig
*.xls
*.xlsb
*.xlsm
*.xlsx
*.xltm
*.xltx
*.xz
*.z
*.zip
*~
EOF

    # chmod a-w $GITIGNORE_PATH
    if [ ! -z $1 ] ; then
        git add --force $GITIGNORE_PATH
        echo "-"
    fi
}


# Add/tweak .gitignore files to get a git repository of moderate size
append_gitignore_lines <<EOF

# At top level track only the matlab directory (sole exception)
#
/*/
!/matlab/
!/config/


# Files (top level, no exceptions)
#
/.clusterdestination
/.last_sunc
/.metadata
/.perforce
/.rtags-config
/.sbcheck.*
/build.glnxa64.log
/changes.sbsmartbuild.mk
/COMMIT_MSG_*
/force.txt*
/GPATH
/GRTAGS
/GTAGS
/ID
/mw_anchor
/sbcheck.cfg
/sblocalhub_items_in_use.json
/sbpatch_history*
/sbrestore_*.txt
/*.log
/*.sbsmartbuild.mk
EOF

# These rules simply define which parts of the directory tree we want to track in git

append_gitignore_lines matlab/ <<EOF
/*/
!/config/
!/src/
!/test/
!/toolbox/
EOF

# These rules reflect the contents of cg_ir/ez.mk (/include/... has mfl stuff)

append_gitignore_lines matlab/src/ <<EOF
/*/
!/cg_ir/
!/cgir_*/
!/dnn_core/
!/eml/
!/emlcoder/
!/half_precision/
!/include/
!/pir_core/
!/range_services/
!/rtw*/
!/slcg/
!/slcg_cpp/
!/slcg_driver/
!/slcg_fe/
!/slcg_filepackaging/
!/slcg_identifiers/
!/slcg_mf0/
!/slvm/
!/xil_utils/
EOF

append_gitignore_lines matlab/src/cg_ir/ <<EOF
MathWorksVSTools/
*.exe
EOF

append_gitignore_lines matlab/src/cgir_hdl/unittest/gold/ <<EOF
*
EOF

append_gitignore_lines matlab/src/cgir_xform/perftests/ <<EOF
*
EOF

append_gitignore_lines matlab/src/cgir_vm/perftests/ <<EOF
*
EOF

append_gitignore_lines matlab/src/slcg_cpp/ <<EOF
/*/
!/client/
EOF

append_gitignore_lines matlab/test/ <<EOF
/*/
!/toolbox/
EOF

append_gitignore_lines matlab/test/toolbox/ <<EOF
/*/
!/cgir/
!/cgir_web_interface/
!/cpp_perf_tests/
EOF

append_gitignore_lines matlab/toolbox/ <<EOF
/*/
!/cgir/
!/coder/
!/shared/
EOF

append_gitignore_lines matlab/toolbox/coder/ <<EOF
/*/
!/codedescriptor_core/
!/foundation/
EOF

append_gitignore_lines matlab/toolbox/shared/ <<EOF
/*/
!/cgir_fe/
!/cgxe/
!/cxxfe/
EOF
