#!/bin/dash

GITDIR=$1
GIT_USER_NAME=$2
GIT_USER_EMAIL=$3

# If this latest cluster image arrived with an embedded .git then delete it
if [ -e .git ]; then
    chmod -R a+w .git
    rm -rf .git
fi

chmod -R a-x mathlab/src

# Ensure this latest_pass is connected to the separate git directory
if [ -d ${GITDIR} ]; then
    # Reconnect to existing separate git dir
    echo "gitdir: ${GITDIR}" >.git
else
    # First time initialization of a separate git dir for this cluster
    git init --separate-git-dir=${GITDIR} .
    git config --local user.name  $GIT_USER_NAME
    git config --local user.email $GIT_USER_EMAIL
fi

# Add/tweak .gitignore files to get a git repository of moderate size
"${SYNCMASTERDIR}/add-git-ignore-files"

# Move the top-level .gitignore to its canonical location
mv .gitignore ${GITDIR}/info/exclude

# If current cluster image does not match repository tip then add and commit
if ! git diff-index --quiet HEAD -- ; then
    # Adding and committing files goes _much_ faster with no compression
    git config --local core.compression 0
    git add config matlab                                                            >/dev/null 2>&1
    sbver                                                                          \
    | sed -nre '/SyncFrom/ s|^.*/(B[^/ ]*)/(.*)_job([0-9]*)_pas.*$|j\3  \2  \1|gp' \
    | git commit -aF -                                                               >/dev/null 2>&1
    # Now repack with extreme compression
    git config --local core.compression 9
    git repack -adfF --threads=0 --depth=50 --window=250 --write-bitmap-index
fi

# Leave behind some stats
SYNC_FROM="$( cd $CLUSTER_PATH ; sbver | grep 'SyncFrom:' )"
echo "$SYNC_FROM" | sed -nre 's|^.*/B[^/]*/(.*)_job.*$|\1|gp'  >${CLUSTERDIR}/WHEN.txt
du -sh ${CLUSTERDIR} | sed -nre 's| *([0-9A-Z]*).*$|\1|p'      >${CLUSTERDIR}/SIZE.txt

# Extend ths list jobs preserved in this repository
echo "$SYNC_FROM" | sed -nre 's|^.*_job([0-9]*).*$|\1|gp'     >>${CLUSTERDIR}/JOBS.txt
JOBS="$( cat ${CLUSTERDIR}/JOBS.txt | /usr/bin/sort -u )"
echo "$JOBS"                                                   >${CLUSTERDIR}/JOBS.txt
