#!/bin/dash

GITDIR=$1
GIT_USER_NAME=$2
GIT_USER_EMAIL=$3

# If this latest cluster image arrived with an embedded .git then delete it
if [ -e .git ]; then
    chmod -R a+w .git
    rm -rf .git
fi

# Ensure this latest_pass is connected to the separate git directory
if [ -d ${GITDIR} ]; then
    # Reconnect to existing separate git dir
    echo "gitdir: ${GITDIR}" >.git
else
    # First time initialization of a separate git dir for this cluster
    git init --separate-git-dir=${GITDIR} .
    git config --local user.name  $GIT_USER_NAME
    git config --local user.email $GIT_USER_EMAIL
fi

# Add/tweak .gitignore files to get a git repository of moderate size
"${SYNCMASTERDIR}/add-git-ignore-files"

# Move the top-level .gitignore to its canonical location
mv .gitignore ${GITDIR}/info/exclude

# If current cluster image does not match repository tip then add and commit
if [ ! git diff-index --quiet HEAD -- ]; then
    git config --local core.compression 0
    time -p git add . >/dev/null 2>&1
    time -p sbver | sed -nre '/SyncFrom/ s|^.*/(B[^/ ]*)/(.*)_job[0-9]*_pass$|\1: \2|gp' | git commit -aF - >/dev/null 2>&1
    # Now repack with maximal compression
    git config --local core.compression 9
    time -p git repack -adfF --threads=0 --depth=50 --window=250 --write-bitmap-index
fi

# Do not propagated the "filesystem-agnostic Git symbolic link" during sbclone
chmod -R a+w .git
rm -rf .git

# Leave behind some stats
SYNC_FROM="$( cd $CLUSTER_PATH ; sbver | grep 'SyncFrom:' )"
echo "$SYNC_FROM" | sed -nre 's|^.*/B[^/]*/(.*)_job.*$|\1|gp'  >${CLUSTERDIR}/WHEN.txt
du -sh ${CLUSTERDIR} | sed -nre 's| *([0-9A-Z]*).*$|\1|p'      >${CLUSTERDIR}/SIZE.txt

# Extend ths list jobs preserved in this repository
echo "$SYNC_FROM" | sed -nre 's|^.*_job([0-9]*).*$|\1|gp'     >>${CLUSTERDIR}/JOBS.txt
JOBS="$( cat ${CLUSTERDIR}/JOBS.txt | /usr/bin/sort -u )"
echo "$JOBS"                                                   >${CLUSTERDIR}/JOBS.txt
