#!/bin/bash

if [ "${SYNCMASTERDIR}"  == "" ] ||
   [ "${CLUSTER}"        == "" ] ||
   [ "${CLUSTERS_ROOT}"  == "" ] ||
   [ "${CLUSTERDIR}"     == "" ] ||
   [ "${CLUSTER_PATH}"   == "" ] ||
   [ "${LOGDIR}"         == "" ] ||
   [ "${GITDIR}"         == "" ] ||
   [ "${GIT_USER_NAME}"  == "" ] ||
   [ "${GIT_USER_EMAIL}" == "" ]
then
    echo
    echo "One or more required environment symbols is not defined:"
    echo
    echo "  SYNCMASTERDIR  = ${SYNCMASTERDIR}"
    echo "  CLUSTER        = ${CLUSTER}"
    echo "  CLUSTERS_ROOT  = ${CLUSTERS_ROOT}"
    echo "  CLUSTERDIR     = ${CLUSTERDIR}"
    echo "  CLUSTER_PATH   = ${CLUSTER_PATH}"
    echo "  LOGDIR         = ${LOGDIR}"
    echo "  GITDIR         = ${GITDIR}"
    echo "  GIT_USER_NAME  = ${GIT_USER_NAME}"
    echo "  GIT_USER_EMAIL = ${GIT_USER_EMAIL}"
    echo
    echo "Did you invoke the script manually without providing these symbols?"
    echo
    echo "A manual invocation might look like:"
    echo
    echo "  CLUSTER=<Bcluster> ~/.sbsyncmaster/env.sh"
    echo
    exit 1
fi

#   echo "sbsyncmaster -no-perforce -no-sbstop -nice -C ${CLUSTERDIR} -src-root ${CLUSTER}:latest_pass -log-dir ${LOGDIR} -cfg ${SYNCMASTERDIR}/git-enabled-workspace.cfg"

sbsyncmaster -no-perforce -no-sbstop -nice -C ${CLUSTERDIR} -src-root ${CLUSTER}:latest_pass -log-dir ${LOGDIR} -cfg ${SYNCMASTERDIR}/git-enabled-workspace.cfg
