#!/bin/dash

export SBSYNCMASTER_SINGLETON=/tmp/sbsyncmaster.running

# If another instance of this script is already running then exit
if [ -e $SBSYNCMASTER_SINGLETON ]; then
    exit
fi

export SYNCMASTERDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
export MAKE_SCRIPT=/hub/share/sbtools/bin/glnxa64/sbmake

### Identify ourselves for git
export GIT_USER_NAME="John Yates"
export GIT_USER_EMAIL=jyates@mathworks.com

# Should match $HOME/.profile
export CCACHE_DIR=/ccc
export CCACHE_LOGFILE=/ccc/LOGFILE
export CCACHE_SLOPPINESS=include_file_mtime,file_macro,time_macros
export CCACHE_TEMPDIR=/huge/ccache
export USE_CCACHE=1

readonly ROOT=/ws

# $ROOT                 <ROOT>/
#                       │
# $CLUSTER_TAG          ├── <CLUSTER_TAG> -> $CLUSTER_LATEST_PASS
#                       │
# $CLUSTER_ROOT         ├── .cluster/
# $CLUSTER_PATH         │   └── <CLUSTER>/
#                       │       ├── ...
# $CLUSTER_LATEST_PASS  │       └── <CLUSTER>.latest_pass/
#                       │
#                       ├── <SANDBOX>/
#                       │           └── ...
#                       │
#                       └── .sandbox/
#                           └── ...

for TAG_PATH in $ROOT/* ; do
    if [ -h $TAG_PATH ]; then
        CLUSTER_LATEST_PASS=$( readlink $TAG_PATH )
        $SYNCMASTERDIR/sync-one-cluster $CLUSTER_LATEST_PASS
    fi
done
