#!/bin/bash

if [ "${SYNCMASTERDIR}"  == "" ] ||
   [ "${LATESTPASSDIR}"  == "" ] ||
   [ "${GIT_USER_NAME}"  == "" ] ||
   [ "${GIT_USER_EMAIL}" == "" ] ||
   [ "${CLUSTER}"        == "" ]
then
    echo
    echo "One or more required environment symbols is not defined:"
    echo
    echo "  SYNCMASTERDIR  = ${SYNCMASTERDIR}"
    echo "  LATESTPASSDIR  = ${LATESTPASSDIR}"
    echo "  GIT_USER_NAME  = ${GIT_USER_NAME}"
    echo "  GIT_USER_EMAIL = ${GIT_USER_EMAIL}"
    echo "  CLUSTER        = ${CLUSTER}"
    echo
    echo "Did you invoke the script manually without providing these symbols?"
    echo
    echo "A manual invocation might look like:"
    echo
    echo "  CLUSTER=<Bcluster> ~/.sbsyncmaster/env.sh"
    echo
    exit 1
fi

LOGDIR=${SYNCMASTERDIR}/${CLUSTER}.logs

sbsyncmaster -no-perforce -no-sbstop -nice -C ${LATESTPASSDIR} -src-root ${CLUSTER}:latest_pass -log-dir ${LOGDIR} -cfg ${SYNCMASTERDIR}/git-enabled-workspace.cfg
